analyzer:
  exclude:
    - flutter_frontend_server/test/fixtures/lib/main.dart
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    always_specify_types: error
    missing_required_param: error
    missing_return: error
    native_function_body_in_non_sdk_code: ignore
    todo: error
    unnecessary_null_comparison: error

linter:
  rules:
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - empty_catches
    - file_names
    - hash_and_equals
    - no_duplicate_case_values
    - non_constant_identifier_names
    - package_prefixed_library_names
    - prefer_generic_function_type_aliases
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_typing_uninitialized_variables
    - provide_deprecation_message
    - unnecessary_overrides
    - unrelated_type_equality_checks
    - valid_regexps
    - void_checks
    - avoid_annotating_with_dynamic
    - always_put_required_named_parameters_first
    - annotate_overrides
    - avoid_classes_with_only_static_members
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_return_types_on_setters
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - avoid_returning_null_for_void
    - avoid_slow_async_io
    - cancel_subscriptions
    - library_prefixes
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_null_aware_operators
    - avoid_final_parameters
    - invariant_booleans
    - avoid_print
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_setters_without_getters
    - avoid_types_on_closure_parameters
    - avoid_void_async
    - prefer_asserts_in_initializer_lists
    - prefer_asserts_with_message
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_const_declarations
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_inlined_adds
    - prefer_mixin
    - prefer_null_aware_method_calls
    - prefer_relative_imports
    - prefer_single_quotes
    - prefer_spread_collections
    - prefer_void_to_null
    - require_trailing_commas
    - sort_child_properties_last
    - type_annotate_public_apis
    - unnecessary_await_in_return
    - unnecessary_getters_setters
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - use_late_for_private_fields_and_variables
    - use_rethrow_when_possible
    - use_setters_to_change_properties
    - use_string_buffers
    - use_super_parameters
    - use_test_throws_matchers
    - use_to_and_as_if_applicable